[package]
name = "mandel-zoom-frames"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", features = ["rayon"] }
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
num_cpus = "1.16"

[profile.release]
opt-level = 3
# lto = true         # Enable Link-Time Optimization
# codegen-units = 1  # Helps LTO optimize more effectively
# strip = true       # Automatically strip symbols from the binary.
# panic = 'abort'    # or 'unwind' for safe memory cleanup
